language: java
jdk: oraclejdk8
after_success:
  - echo "<settings><servers><server><id>deployment</id><username>\${env.SONATYPE_USER}</username><password>\${env.SONATYPE_PASS}</password></server></servers></settings>" > ~/settings.xml
  - mvn deploy -DupdateReleaseInfo=true --settings ~/settings.xml